---
- name: install hex
  shell: mix local.hex --force
  args:
    creates: ~/.mix/archives/hex-*
  register: hex

- name: install rebar
  shell: mix local.rebar --force
  args:
    creates: ~/.mix/rebar3
  register: rebar

- name: install phoenix
  shell: mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez --force
  args:
    creates: ~/.mix/archives/phx_new
  register: phoenix
