---

- name: deploy | prerequisites
  hosts: all
  become: yes
  become_user: echotrap
  vars:
    site_dir: /home/echotrap/www/echotrap.com
  tasks:
    - name: create site folder (if needed)
      file:
        path: "{{ site_dir }}"
        state: directory

    - name: clone repo
      git:
        repo: "https://github.com/delameko/echotrap.git"
        dest: "{{ site_dir }}"

